[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/y-akbal/Tedu_Time_Series/blob/main/W1/W1P2.ipynb)


In [ ]:
import numpy as np  ### convention

In [ ]:
A = np.array([1,2,3])

In [ ]:
A.size

3

In [ ]:
dir(A)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
A = np.array([-1, 3, -4,-5])


-1.75

#How to create a random vector?

In [ ]:
dir(np.random)  ### below you will see distributions!

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [ ]:
np.random.poisson(2,size = (15,5))   ### a random sample from poisson distribution with mean 2.

array([[1, 0, 1, 2, 3],
       [0, 0, 4, 2, 0],
       [0, 4, 3, 2, 5],
       [1, 3, 1, 1, 0],
       [3, 1, 4, 1, 5],
       [0, 1, 0, 2, 1],
       [0, 1, 1, 0, 3],
       [1, 0, 1, 4, 1],
       [1, 5, 5, 1, 0],
       [2, 0, 0, 2, 5],
       [2, 3, 3, 4, 2],
       [2, 4, 2, 2, 1],
       [1, 1, 3, 1, 2],
       [1, 1, 5, 0, 1],
       [2, 1, 1, 3, 3]])

In [ ]:
np.random.randn(10,10)   #### A sample from standard normal distribution 

array([[-0.5488574 ,  0.07451804,  0.40974324, -1.38248833,  0.54315797,
         0.15990191,  0.82165858, -0.57754987,  0.76954011, -0.24276442],
       [ 1.24599722,  0.48550237,  0.21667497,  0.35348487,  0.83872927,
        -0.70504037,  0.89917484, -0.17601108, -0.83138966,  1.31745624],
       [-0.13649173,  0.30471881, -1.1635087 ,  0.06290089,  0.19784877,
        -0.42200335,  0.37988746, -0.33415715,  0.81658285,  0.00345952],
       [ 0.6006006 , -0.90660861,  0.80751153,  0.70844472,  1.10094923,
         1.11739022, -1.57929679, -1.1498469 , -0.08110646,  0.68247721],
       [ 1.22348885,  1.57549826,  0.18775277,  0.888301  ,  0.13141953,
         1.99729129, -0.71066061,  0.66969809,  0.38399845,  1.33593614],
       [ 0.172335  , -0.59036802,  0.80206595, -0.545662  ,  1.19146876,
         0.32416154, -0.40641478,  1.58974925,  1.16081473,  0.02742256],
       [ 0.46118468,  0.55053549, -0.56542268, -0.06059244, -0.23740863,
        -0.31870239,  0.12543778, -1.15532907

In [ ]:
np.random.normal()

In [ ]:
np.random.normal(0, 2, size = (10,10)) #### fixing variable and variance

array([[ 1.83672497e+00,  2.50336380e-01,  1.68212014e+00,
        -1.92034359e+00,  4.05075505e+00, -1.05808177e+00,
        -2.18872687e+00, -9.32791468e-02,  4.04723414e+00,
         4.93103737e-01],
       [-2.20596541e+00,  7.51828984e-01, -1.89279803e+00,
        -7.58920520e-01,  3.80915475e+00, -2.16687668e+00,
        -1.19927731e+00,  3.64156048e+00,  3.23865224e+00,
        -1.50484994e+00],
       [ 1.73015533e+00, -1.70177888e+00, -2.46322498e+00,
        -8.01762697e-01, -5.27544543e-01, -6.43027589e-01,
         1.24971999e+00,  8.79971768e-01, -2.43741191e+00,
         1.65891433e+00],
       [ 1.26299677e+00, -2.13531497e+00, -8.01027471e-01,
         6.07117200e-01,  1.81354588e+00,  2.79749305e-01,
         3.22209127e+00, -1.31897810e+00, -1.97611893e+00,
        -2.16305066e+00],
       [ 7.34449492e-01,  2.36441558e+00,  2.11946559e+00,
        -2.07024431e+00, -1.56197173e+00, -1.75122989e+00,
         2.82710133e+00,  2.95672786e+00,  1.02045833e+00,
         2.

In [ ]:
np.random.chisquare(2, size = (10,10))  ### sample from chi^2 distribution with degrees of freedom 2.

array([[ 0.64346096,  3.54092207,  1.1343734 ,  0.36856507,  3.399196  ,
         2.55577044,  0.22162204,  0.45344388,  1.35571885,  1.57360512],
       [ 1.1331174 ,  7.67418182,  4.03908773,  0.50290975,  4.4509021 ,
         1.71425432,  0.19524011,  3.94306983,  0.63736398,  2.74207102],
       [ 1.48381774,  4.57660677,  1.71590934,  0.83792841, 15.8850071 ,
         3.94639666,  0.83765125,  1.85105864,  1.00483959,  1.9191265 ],
       [ 5.28211439,  0.80587304,  0.32964316,  3.1073994 ,  1.79737147,
         0.95609116,  1.56384824,  0.66256818,  1.630902  ,  0.94606656],
       [ 3.69627498,  2.41538208,  1.91495699,  3.91213534,  0.5721589 ,
         7.43830172,  0.63223785,  2.37764388,  7.26313282,  0.98104356],
       [ 5.77630902,  0.1583518 ,  1.55694142,  0.05460577,  1.54055601,
         0.76507702,  8.09197491,  1.42624403,  2.60368805,  1.96655979],
       [ 3.58781151, 10.78501027,  1.43797977,  0.46824828,  3.18231915,
         2.1517101 ,  2.04930729,  1.89867962

In [ ]:
5*np.random.standard_t(5, size = (10,2))  ### student's t-distribution!

NameError: ignored

In [ ]:
for i in np.arange(1,10,0.125):
  print(i)

1.0
1.125
1.25
1.375
1.5
1.625
1.75
1.875
2.0
2.125
2.25
2.375
2.5
2.625
2.75
2.875
3.0
3.125
3.25
3.375
3.5
3.625
3.75
3.875
4.0
4.125
4.25
4.375
4.5
4.625
4.75
4.875
5.0
5.125
5.25
5.375
5.5
5.625
5.75
5.875
6.0
6.125
6.25
6.375
6.5
6.625
6.75
6.875
7.0
7.125
7.25
7.375
7.5
7.625
7.75
7.875
8.0
8.125
8.25
8.375
8.5
8.625
8.75
8.875
9.0
9.125
9.25
9.375
9.5
9.625
9.75
9.875


#Numpy arrays of the same size can be summed

In [ ]:
A = np.random.randn(10,10)
B = np.random.randn(10,5)

In [ ]:
A+B

ValueError: ignored

In [ ]:
B.shape

(10, 10)

#Numpy arrays of the same size can be multiplied as matrices


In [ ]:
B = np.random.randn(10,10)
C = np.random.randn(10,10)
T = np.dot(B,C)  #### as a matrix B*C
print(T)


[[ 4.02346213e-01 -1.81863044e+00  1.25387584e+00  1.51087133e+00
   1.55939193e+00 -1.29271232e+00 -1.58904307e+00  5.48587721e-01
  -6.78075051e+00  1.55481821e+00]
 [-8.62705697e-01 -5.09342079e+00  4.54673843e+00 -2.97540183e+00
  -5.32610719e-01  1.70500459e+00  5.62389811e+00  2.33528012e+00
   1.89886971e+00 -1.80175367e+00]
 [ 1.93689817e+00  2.41297075e+00 -1.13778292e+00  2.98883963e+00
  -1.73264831e+00  5.50349363e-01 -4.38564328e-01 -2.06700598e-01
  -3.83077114e+00  1.73391011e+00]
 [-3.85793270e+00  3.11819305e+00  7.86246064e+00 -7.07054298e+00
   6.70016310e+00  3.87243832e+00 -1.44236633e+01  8.22680533e-01
  -9.89737178e-01 -2.75170433e+00]
 [-4.10157145e+00  2.49860177e+00  1.75175020e+00  4.33011430e-01
   3.13180449e+00  3.10428626e+00  2.63651956e+00 -1.51536433e+00
   2.98906308e+00 -4.47711044e+00]
 [ 5.02618827e-01  1.23281800e+00 -1.45230879e+00  1.96148463e+00
  -4.68976789e+00  2.16745851e-01  7.86731370e+00 -8.97235081e-01
  -9.87808680e-01  5.79281133e-01

In [ ]:
np.array_equal(np.dot(B,C), np.matmul(B,C))  ### this arrays are not equal because B*C is component wise multiplication

True

In [ ]:
A = np.random.randn(10,1)
B = np.ones(shape = (10,1))
A*B


array([[ 0.81744244],
       [ 0.51620434],
       [-1.29345934],
       [-0.24994416],
       [-0.27699837],
       [-0.97490915],
       [ 1.50900395],
       [ 0.23770674],
       [ 0.14954222],
       [-0.02218436]])

In [ ]:
A

array([[ 0.81744244],
       [ 0.51620434],
       [-1.29345934],
       [-0.24994416],
       [-0.27699837],
       [-0.97490915],
       [ 1.50900395],
       [ 0.23770674],
       [ 0.14954222],
       [-0.02218436]])

#Broadcasting

In [ ]:
np.random.randn(10,10)+1  ###adds one to each entry of this array!

array([[ 0.48833085,  1.37005344,  0.65819455,  0.8341764 ,  1.34512151,
         1.07526605, -1.13635851,  0.65419156,  2.08989915,  1.22998668],
       [-0.21690185,  2.54329364,  0.45877345,  0.37210198,  2.83703908,
         1.14450366,  1.06085398,  1.18390309,  0.52212349, -0.06376369],
       [ 0.86312892,  0.0978138 ,  1.52027018,  1.40097177,  1.04976497,
         1.08024622,  1.07221952,  2.24675022,  0.25648746,  2.60408019],
       [ 0.20987121,  1.72257216, -0.08887901,  0.829992  ,  2.39953689,
         0.93389303,  3.191806  ,  2.52418126, -0.00926314,  0.7126918 ],
       [ 0.99310004,  1.32411077,  1.37717496,  0.70273278,  0.13191898,
         2.08393866, -0.34174548,  1.41166844,  2.16049273,  0.24090572],
       [-1.30117024,  1.66154755,  1.57510389,  1.5226554 ,  1.67767769,
         2.67834398,  0.24629706,  1.07698157,  0.50455932,  0.66341806],
       [ 0.79014703, -0.32966271,  1.01171051,  1.09567406,  1.07175676,
         1.95492621,  0.55946609,  1.30779224

# To sort a numpy array

In [ ]:
A = np.random.randn(10,1)
A.sort()

In [ ]:
A

array([[ 0.90228808],
       [-0.73135981],
       [-1.60423742],
       [-1.98049947],
       [ 2.11542126],
       [ 0.33171222],
       [-0.3783826 ],
       [-1.72758736],
       [-0.62816906],
       [-0.00567022]])

In [ ]:
np.argmax(A)


2.115421263471085

#Numpy arrays can be flattened and  reshaped

In [ ]:
B = B.reshape(100)  #### or B.reshape(100,-1)
print(B)

[-1.37447883  0.59862735 -1.13067725  0.28495439  1.49045579  0.11891505
 -1.06910496 -1.43304021 -2.31302528  0.50541901 -1.37071326 -0.09524423
 -0.4354355  -0.87440371 -0.76296495 -0.84232568 -0.1363115  -0.45350296
  0.37272498  0.0854825  -0.34626817  2.24792084 -1.36663445 -0.2467573
 -0.49267727  0.69235666  2.6346236   1.75817333 -1.89959522  0.42791584
 -0.26205951  1.24449874 -0.10330378 -0.51027736 -1.07662355 -0.01202913
  1.22224457 -0.60802753  0.22391229  0.26102544 -0.47450672 -0.30831306
 -0.09425789  0.6375727   0.61759566 -0.86488691 -2.03972355  1.05714859
  1.41895696  0.62309026 -0.24715697  0.23168096  0.4763678   1.40565378
  0.46295347  0.57693824  0.3626274  -0.1819345  -0.31151658  0.87710972
 -0.6611845  -1.00719419  0.16837211  0.31575509 -0.55502851  1.30197262
  0.0844287  -1.15256536 -2.11379078  1.01688383 -0.17394631 -0.91922386
 -0.77029413  0.22996658  0.04369402 -0.84543648 -0.128274   -0.52962898
 -0.17127975  0.69010008  0.58581052 -0.04790687 -1.

In [ ]:
B = np.random.randn(10,10,10)   ### this dude is called a tensor there are 10 layers of 10*10 numpy arrays


#The first axis is called 0, and then 1 and then 2.

In [ ]:
np.mean(B, axis = 2)

array([[-0.23696548,  0.20925573,  0.11554417, -0.45270859, -0.12114058,
         0.04295383,  0.30893626, -0.0677464 ,  0.21744455,  0.17671783],
       [ 0.37641662, -0.23257985, -0.03494298, -0.31777841, -0.49304044,
         0.49405572, -0.20313529, -0.04294131, -0.05271124,  0.1277096 ],
       [-0.188059  , -0.06058643,  0.51899076, -0.14497318, -0.49427151,
        -0.3110461 , -0.3907418 , -0.77646992, -0.0322055 , -0.35724467],
       [-0.10449733, -0.17208896, -0.41126024, -0.51406107, -0.12985774,
         0.08800023,  0.50949297,  0.29842856,  0.45766947, -0.6661693 ],
       [ 0.55890218,  0.10805924,  0.03663236, -0.25504164, -0.42251794,
        -0.28505203, -0.29000171, -0.06717122,  0.54938463, -0.27055613],
       [-0.04313324, -0.12383587,  0.13977199,  0.38361451,  0.11374033,
         0.13880326, -0.10442443, -0.01261321,  0.38813518,  0.52612423],
       [-0.06247853, -0.17499397,  0.09627467,  0.23459337, -0.06448128,
        -0.0740891 ,  0.19231164, -0.44120461

# Simple functions can directly be applied to numpy arrays

In [ ]:
f = lambda x: x**2
x = np.random.randn(10)
f(x)

NameError: ignored